[Service]
RestrictSUIDSGID=yes
ProtectSystem=true
ProtectProc=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectHome=true
ProtectControlGroups=true
ProtectClock=true
