[Service]
RestrictNamespaces=true
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
# XXX test
SystemCallFilter=@file-system @io-event @process @signal @sync

PrivateUsers=true
PrivateTmp=true
# XXX is it more secure to hide mounts from init?
PrivateMounts=true
PrivateDevices=true
NoNewPrivileges=true

# default is OK?
#KeyringMode=inherit
# not needed PrivateDevices=true
#DeviceAllow=
# XXX what does this even mean?
#CapabilityBoundingSet=

# upon user discretion, locally
#IPAddressAllow=
